from dataclasses import dataclass
from datetime import datetime

@dataclass
class fact:
    id_basica: int
    nr_voo: int
    nr_singular: int
    dt_referencia: datetime
    nr_ano_referencia: int
    nr_semestre_referencia: int
    nm_semestre_referencia: str
    nr_trimestre_referencia: int
    nm_trimestre_referencia: str
    nr_mes_referencia: int
    nm_mes_referencia: str
    nr_semana_referencia: int
    nm_dia_semana_referencia: str
    nr_dia_referencia: int
    nr_ano_mes_referencia: int
    hr_partida_real: datetime.hour
    dt_partida_real: datetime
    nr_ano_partida_real: int
    nr_semestre_partida_real: int
    nm_semestre_partida_real: str
    nr_trimestre_partida_real: int
    nm_trimestre_partida_real: str
    nr_mes_partida_real: int
    nm_mes_partida_real: str
    nr_semana_partida_real: int
    nm_dia_semana_partida_real: str
    nr_dia_partida_real: int
    nr_ano_mes_partida_real: int
    nr_etapa: int
    hr_chegada_real: datetime.hour
    dt_chegada_real: datetime
    nr_ano_chegada_real: int
    nr_semestre_chegada_real: int
    nm_semestre_chegada_real: str
    nr_trimestre_chegada_real: int
    nm_trimestre_chegada_real: str
    nr_mes_chegada_real: int
    nm_mes_chegada_real: str
    nr_semana_chegada_real: int
    nm_dia_semana_chegada_real: str
    nr_dia_chegada_real: int
    nr_ano_mes_chegada_real: int
    nr_escala_destino: int
    lt_combustivel: float
    nr_assentos_ofertados: float
    kg_payload: float
    km_distancia: float
    nr_passag_pagos: float
    nr_passag_gratis: float
    kg_bagagem_livre: float
    kg_bagagem_excesso: float
    kg_carga_paga: float
    kg_carga_gratis: float
    kg_correio: float
    nr_decolagem: float
    nr_horas_voadas: float
    kg_peso: float
    nr_velocidade_media: float
    nr_pax_gratis_km: float
    nr_carga_paga_km: float
    nr_carga_gratis_km: float
    nr_correio_km: float
    nr_bagagem_paga_km: float
    nr_bagagem_gratis_km: float
    nr_ask: float
    nr_rpk: float
    nr_atk: float
    nr_rtk: float
    id_arquivo: int
    nm_arquivo: str
    nr_linha: int
    dt_sistema: datetime
